config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "callbacks" }

  root to: "welcome#index"

  resources :dashboard
  get "new_gist", to: "dashboard#new_gist", as: "new_gist"
  post "create_gist", to: "dashboard#create_gist", as: "create_gist"
  get "gists/:login", to: "dashboard#gists", as: "gists"
  get "gist_content(/:gistid)", to: "dashboard#gist_content", as: "gist_content"
  delete "delete_gist(/:gistid)", to: "dashboard#delete_gist", as: "delete_gist"
  put "star_gist(/:gistid)", to: "dashboard#star_gist", as: "star_gist"
  put "unstar_gist(/:gistid)", to: "dashboard#unstar_gist", as: "unstar_gist"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gist.rb
# frozen_string_literal: true

class Gist
  include ActiveModel::Model

  class File
    include ActiveModel::Model

    attr_accessor :filename, :content
    validates :content, presence: true

    def new_record?
      true
    end

    def marked_for_destruction?
      false
    end
  end

  attr_accessor :description, :public, :files
  validates :files, presence: true

  def files
    @files ||= []
  end

  def files_attributes=(attributes)
    @files = attributes.map do |file_params|
      next nil if file_params[:content].blank?

      Gist::File.new(file_params)
    end.compact
  end

  def build_file(file_attributes = {})
    Gist::File.new(file_attributes)
  end

  def valid?
    is_valid = super & files.map(&:valid?).reduce(&:&)

    copy_files_errors_to_gist

    is_valid
  end

  def create_payload
    {
      description: description,
      public: ActiveRecord::Type::Boolean.new.cast(public),
      files: format_files
    }
  end

  private

  def format_files
    files.each.with_index.each_with_object({}) do |(file, index), memo|
      file.filename = "gistfile#{index + 1}.txt" if file.filename.blank?

      memo[file.filename] = { content: file.content }
    end
  end

  def copy_files_errors_to_gist
    files.each do |file|
      next if file.errors.empty?

      file.errors.full_messages.each do |message|
        errors.add(:files, message.downcase)
      end
    end
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :recoverable, :rememberable, :validatable, :omniauthable

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.github_login = auth.info.nickname
      user.token = auth['credentials']['token']
      user.password = Devise.friendly_token[0, 20]
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/callbacks_controller.rb
# frozen_string_literal: true

class CallbacksController < Devise::OmniauthCallbacksController
  def github
    @user = User.from_omniauth(request.env['omniauth.auth'])
    sign_in_and_redirect @user
  end
end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

class DashboardController < ApplicationController
  include DashboardHelper
  before_action :authenticate_user!

  def index
    @following = current_client.following
    @followers = current_client.followers
  end

  def gists
    @owner = params[:login]

    @gists =
      if @owner == current_client.login
        owner_gists(params)
      else
        Octokit.gists(@owner)
      end

    @gists = star_starred_gists(@gists)
  end

  def gist_content
    @gist = Octokit.gist(params[:id])
    respond_to do |format|
      format.html { redirect_to @gist.url }
      format.js
    end
  end

  def star_gist
    gist_action('star')
  end

  def unstar_gist
    gist_action('unstar')
  end

  def delete_gist
    gist_action('delete')
  end

  def new_gist
    @gist = Gist.new(files: [Gist::File.new])
  end

  def create_gist
    @gist = Gist.new create_gist_params

    if @gist.valid?
      resource_response = current_client.create_gist @gist.create_payload

      if current_client.last_response.status == 201
        flash[:success] = <<~TXT.squish
          The gist was successfully created at #{resource_response[:html_url]}
        TXT
        redirect_to root_path
      else
        flash[:danger] = "We couldn't create the gist."
        render :new_gist
      end
    else
      render :new_gist
    end
  end

  private

  def create_gist_params
    params.require(:gist).permit(
      :description,
      :public,
      files_attributes: [:filename, :content, :_destroy]
    )
  end

  def star_starred_gists(gists)
    current_client_starred_gist_ids = current_client.starred_gists.pluck(:id)

    gists.each do |gist|
      gist.starred = current_client_starred_gist_ids.include?(gist.id)
    end.partition(&:starred).flatten
  end

  def owner_gists(params)
    case params[:filter]
    when 'public'
      Octokit.gists(@owner)
    when 'starred'
      current_client.starred_gists.each { |gist| gist.starred = true }
    else
      current_client.gists
    end
  end
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  def index
    redirect_to dashboard_index_path if user_signed_in?
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/dashboard_helper.rb
# frozen_string_literal: true

module DashboardHelper
  def stack
    Faraday::RackBuilder.new do |builder|
      builder.use Faraday::HttpCache, serializer: Marshal, shared_cache: false
      builder.use Octokit::Response::RaiseError
      builder.adapter Faraday.default_adapter
    end
  end

  def client
    Octokit.middleware = stack
    client = Octokit::Client.new(user: current_user.github_login, access_token: current_user.token)
    client.auto_paginate = true
    client
  end

  def current_client
    @current_client ||= client
  end

  def gist_action(action)
    respond_to do |format|
      format.html { redirect_to Octokit.gist(params[:id]).url }
      format.js do
        unless current_client.send("#{action}_gist", params[:id])
          render json: { error: "Couldn't #{action} the gist" }
        end
      end
    end
  end

  # twitter_id = twitter user ID
  # twitter_users = Enumerable with .id method, that returns user id
  # Compares a twitter_id if it finds a match based on the provided twitter_users
  # much faster than doing client.follows?
  # TODO: move to a twitter helper instead.
  def following?(twitter_id, twitter_users)
    twitter_users.any? { |user| twitter_id == user.id }
  end
end

app/helpers/kramdown_helper.rb
# frozen_string_literal: true

module KramdownHelper
  require 'kramdown'
  require 'rouge'

  def format_collection(content_collection)
    filecontent_html = ''
    content_collection.each do |filename, details|
      filecontent_html << "<h5>#{filename}</h5><hr><div>#{file_preview(details)}</div>"
    end
    filecontent_html
  end

  def file_preview(details)
    if /image/.match?(details[:type])
      image_tag(details[:raw_url], alt: details[:filename])
    else
      kramdown_rouge_prepare(details[:content], details[:language])
    end
  end

  def kramdown_rouge_prepare(text, lang)
    lang ||= 'txt' # Lang shoud be nil. Set default as txt
    formatter = Rouge::Formatters::HTMLLegacy.new(line_numbers: false, css_class: 'highlight')
    if lang == 'Markdown'
      sanitize Kramdown::Document.new(text, smart_quotes: 'lsquo,rsquo,ldquo,rdquo',
                                            entity_output: 'as_char',
                                            toc_levels: '1..6',
                                            auto_ids: false,
                                            footnote_nr: 1,
                                            show_warnings: true,
                                            syntax_highlighter: 'rouge',
                                            syntax_highlighter_opts: {
                                              default_lang: lang || 'plaintext',
                                              bold_every: 8,
                                              css: :class,
                                              css_class: 'highlight',
                                              formatter: formatter
                                            }).to_html
    else
      lexer = Rouge::Lexer.find(lang.downcase) || Rouge::Lexer.find('plaintext')
      formatter.format(lexer.lex(text))
    end
  end
end

app/views/application/_alert.html.erb
<% type_to_alert_modifier_class = Hash.new do |hash, key| %>
  <% if key == "alert" %>
    <% hash[key] = "alert-danger" %>
  <% elsif key == "notice" %>
    <% hash[key] = "alert-primary" %>
  <% else %>
    <% hash[key] = "alert-#{key}" %>
  <% end %>
<% end %>

<% flash.each do |type, message| %>
  <div class="alert <%= type_to_alert_modifier_class[type] %> alert-dismissible fade show" role="alert">
    <%= message %>

    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/application/_model_errors.html.erb
<% return if model.errors.empty? %>

<div class="alert alert-danger alert-dismissible fade show" role="alert">
  <%= pluralize(model.errors.count, "error") %> prohibited this <%= model_name %> from being saved:

  <ul class="mb-0">
    <% model.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>

  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/dashboard/_file_fields.html.erb
<div class="nested-fields">
  <div class="form-group">
    <%= f.label :filename %>

    <div class="input-group">
      <%= f.text_field :filename, class: "form-control", placeholder: "Filename including extension…" %>
      <div class="input-group-append" style="display: none">
        <% icon = capture do %>
          <i class="fa fa-trash"></i>
        <% end %>
        <%= link_to_remove_association icon, f, class: "btn btn-outline-secondary" %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, class: "form-control", rows: 15 %>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function() {
    $('.col-12').on('cocoon:after-insert', function() {
      if ($(".form-control").length > 3) {
        $(".input-group-append").each(function(i) {
          $(".input-group-append")[i].style.display = "block";
        });
      }
    });
    .on("cocoon:after-remove", function() {
      if ($(".form-control").length == 3) {
        $(".input-group-append").each(function(i) {
          $(".input-group-append")[i].style.display = "none";
        });
      }
    });
  });
</script>

app/views/dashboard/delete_gist.js.erb
$('<%= "#js-gist-#{params[:id]}-row"%>').fadeOut("slow", function() {
  $(this).remove();
});

app/views/dashboard/get_follower_gists.html.erb
<div class="row">
  <div class="col-auto mr-auto">
    <h3><%= @owner %>'s Gists</h3>
  </div>
  <div class="col-auto right-gap">
    <%= link_to "Back", dashboard_index_path, {class: 'btn btn-sm btn-outline-secondary'} %>
  </div>
</div>
<div class="row">
  <div class="col-12">
    <% if @gists.count == 0 %>
      <div class="gistcatch-box">
        <h6>No gists.</h6>
      </div>
    <% else %>
      <div id="accordion" class="top-gap">
          <% @gists.each do |g| %>
            <% g.files.each do |f| %>
              <div class="container">
                <div class="row">
                  <div class="col-1 card-link">
                    <%= link_to g.starred ? unstar_gist_path(id: g.id) : star_gist_path(id: g.id), remote: true, id: "link-#{g.id}", method: :put do %>
                    <button class="btn btn-outline-secondary col-12 text-left">
                      <i id="icon-<%= g.id %>" class="<%= g.starred ? "fas" : "far" %> fa-star"></i>
                    </button>
                    <% end %>
                  </div>
                  <div class="col-11">
                    <div class="card" style="margin-bottom: 10px;">
                      <div class="card-link" id="card<%=g.id%>">
                        <button class="btn btn-outline-secondary col-12 text-left" data-toggle="collapse" data-target="#collapse<%=g.id%>" aria-expanded="true" aria-controls="collapse<%=g.id%>" ><%= f[0]%>
                        <%= link_to "", {controller: "dashboard", action: "gist_content", id: g.id, remote: true} %>
                        </button>
                        </div>
                      </div>
                  </div>
                </div>
                <div id="collapse<%=g.id%>" class="collapse" aria-labelledby="<%=g.id%>" data-parent="#accordion">
                  <div id="cardcontent<%=g.id%>" class="card-body"></div>
                </div>
              </div>
              <%  break if f.count > 1 %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/dashboard/get_gists.html.erb
<div class="row">
  <div class="col-auto mr-auto">
    <h3><%= @owner %>'s Gists</h3>
  </div>
  <div class="col-auto right-gap">
    <%= link_to "Back", dashboard_index_path, {class: 'btn btn-sm btn-outline-secondary'} %>
  </div>
</div>
<div class="row">
  <% if @owner == current_client.login %>
    <div class="col-12 text-center">
      <div class="btn-group" role="group">
        <%= link_to "All", { filter: "all" }, class: "btn btn-secondary #{params[:filter].presence == 'all' || params[:filter].blank? ? 'active' : ''}" %>
        <%= link_to "Public", { filter: "public" }, class: "btn btn-secondary #{params[:filter] == 'public' ? 'active' : ''}" %>
        <%= link_to "Starred", { filter: "starred" }, class: "btn btn-secondary #{params[:filter] == 'starred' ? 'active' : ''}" %>
      </div>
    </div>
  <% end %>

  <div class="col-12">
    <% if @gists.count == 0 %>
      <div class="gistcatch-box">
        <h6>No gists.</h6>
      </div>
    <% else %>
      <div id="accordion" class="top-gap">
          <% @gists.each do |g| %>
            <% g.files.each do |f| %>
              <div class="container">
                <div class="row" id="js-gist-<%= g.id %>-row">
                  <div class="col-1 card-link">
                    <%= link_to g.starred ? unstar_gist_path(id: g.id) : star_gist_path(id: g.id), remote: true, id: "link-#{g.id}", method: :put do %>
                    <button class="btn btn-outline-secondary col-12 text-left">
                      <i id="icon-<%= g.id %>" class="<%= g.starred ? "fas" : "far" %> fa-star"></i>
                    </button>
                    <% end %>
                  </div>
                  <div class="<%= @owner == current_client.login ? 'col-10' : 'col-11' %>">
                    <div class="card" style="margin-bottom: 10px;">
                      <div class="card-link" id="card<%=g.id%>">
                        <button class="btn btn-outline-secondary col-12 text-left" data-toggle="collapse" data-target="#collapse<%=g.id%>" aria-expanded="true" aria-controls="collapse<%=g.id%>" ><%= f[0]%>
                          <% unless g.public %>
                            <span class="badge badge-light">Secret</span>
                          <% end %>
                        <%= link_to "", {controller: "dashboard", action: "gist_content", id: g.id, remote: true} %>
                        </button>
                        </div>
                      </div>
                  </div>
                  <% if @owner == current_client.login %>
                    <div class="col-1 card-link">
                      <%= link_to delete_gist_path(id: g.id), remote: true, method: :delete, data: { confirm: "Are you sure?" } do %>
                        <button class="btn btn-outline-secondary col-12 text-left">
                          <i class="fa fa-trash"></i>
                        </button>
                      <% end %>
                    </div>
                  <% end %>
                </div>
                <div id="collapse<%=g.id%>" class="collapse" aria-labelledby="<%=g.id%>" data-parent="#accordion">
                  <div id="cardcontent<%=g.id%>" class="card-body"></div>
                </div>
              </div>
              <%  break if f.count > 1 %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/dashboard/gist_content.js.erb
$('<%= "#cardcontent#{@gist.id}"%>').html("<%= escape_javascript(format_collection(@gist.files)).html_safe %>") ;

app/views/dashboard/gists.html.erb
<div class="row">
  <div class="col-auto mr-auto">
    <h3><%= @owner %>'s Gists</h3>
  </div>
  <div class="col-auto right-gap">
    <%= link_to "Back", dashboard_index_path, {class: 'btn btn-sm btn-outline-secondary'} %>
  </div>
</div>
<div class="row">
  <% if @owner == current_client.login %>
    <div class="col-12 text-center">
      <div class="btn-group" role="group">
        <%= link_to "All", { filter: "all" }, class: "btn btn-secondary #{params[:filter].presence == 'all' || params[:filter].blank? ? 'active' : ''}" %>
        <%= link_to "Public", { filter: "public" }, class: "btn btn-secondary #{params[:filter] == 'public' ? 'active' : ''}" %>
        <%= link_to "Starred", { filter: "starred" }, class: "btn btn-secondary #{params[:filter] == 'starred' ? 'active' : ''}" %>
      </div>
    </div>
  <% end %>

  <div class="col-12">
    <% if @gists.count == 0 %>
      <div class="gistcatch-box">
        <h6>No gists.</h6>
      </div>
    <% else %>
      <div id="accordion" class="top-gap">
          <% @gists.each do |g| %>
            <% g.files.each do |f| %>
              <div class="container">
                <div class="row" id="js-gist-<%= g.id %>-row">
                  <div class="col-1 card-link">
                    <%= link_to g.starred ? unstar_gist_path(id: g.id) : star_gist_path(id: g.id), remote: true, id: "link-#{g.id}", method: :put do %>
                    <button class="btn btn-outline-secondary col-12 text-left">
                      <i id="icon-<%= g.id %>" class="<%= g.starred ? "fas" : "far" %> fa-star"></i>
                    </button>
                    <% end %>
                  </div>
                  <div class="<%= @owner == current_client.login ? 'col-10' : 'col-11' %>">
                    <div class="card" style="margin-bottom: 10px;">
                      <div class="card-link" id="card<%=g.id%>">
                        <button class="btn btn-outline-secondary col-12 text-left" data-toggle="collapse" data-target="#collapse<%=g.id%>" aria-expanded="true" aria-controls="collapse<%=g.id%>" ><%= f[0]%>
                          <% unless g.public %>
                            <span class="badge badge-light">Secret</span>
                          <% end %>
                        <%= link_to "", {controller: "dashboard", action: "gist_content", id: g.id, remote: true} %>
                        </button>
                        </div>
                      </div>
                  </div>
                  <% if @owner == current_client.login %>
                    <div class="col-1 card-link">
                      <%= link_to delete_gist_path(id: g.id), remote: true, method: :delete, data: { confirm: "Are you sure?" } do %>
                        <button class="btn btn-outline-secondary col-12 text-left">
                          <i class="fa fa-trash"></i>
                        </button>
                      <% end %>
                    </div>
                  <% end %>
                </div>
                <div id="collapse<%=g.id%>" class="collapse" aria-labelledby="<%=g.id%>" data-parent="#accordion">
                  <div id="cardcontent<%=g.id%>" class="card-body"></div>
                </div>
              </div>
              <%  break if f.count > 1 %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/dashboard/index.html.erb
<ul class="nav nav-pills justify-content">
  <li class="nav-item active">
    <a data-toggle="tab" class="btn btn-info" href="#following">
      Following  <span class="badge badge-pill badge-light"><%= @following.count %></span>
    </a>
    <a data-toggle="tab" class="btn btn-secondary" href="#followers">
      Followers  <span class="badge badge-pill badge-light"><%= @followers.count %></span>
    </a>
  </li>
</ul>
<div class="tab-content top-gap">
  <div id="following" class="tab-pane active">
    <h2 class="text-center cyan-text">Gists from People You Follow</h2>
    <br>
    <% @following.each do |f| %>
      <%= link_to gists_path(f.login), style: "text-decoration: none" do %>
        <div class="card bg-info bg-gradient-info shadow-info border-info mb-3 text-white stampsize">
          <img class="card-img-top" src="<%= f.avatar_url %>" alt="Card image cap">
          <div class="card-block">
            <span class="card-title"><%= f.login %></span>
            <div class='card-status'>
              <%= following?(f.id, @followers) ? "Follows you" : "&nbsp;".html_safe %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <div id="followers" class="tab-pane">
    <h2 class="text-center grey-text">Gists from Your Followers</h2>
    <br>
    <% @followers.each do |f| %>
      <%= link_to gists_path(f.login), style: "text-decoration: none" do %>
        <div class="card bg-secondary mb-3 stampsize follower">
          <img class="card-img-top" src="<%= f.avatar_url %>" alt="Card image cap">
          <div class="card-block">
            <span class="card-title"><%= f.login %></span>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/dashboard/new_gist.html.erb
<div class="row">
  <div class="col-auto mr-auto">
    <h3>New Gist</h3>
  </div>
  <div class="col-auto right-gap">
    <%= link_to "Back", dashboard_index_path, {class: 'btn btn-sm btn-outline-secondary'} %>
  </div>
</div>
<div class="row">
  <div class="col-12">
    <%= form_with model: @gist, url: create_gist_path, method: :post, local: true do |form| %>
      <%= render "model_errors", model: @gist, model_name: "gist" %>

      <div class="form-group">
        <%= form.label :description %>
        <%= form.text_field :description, class: "form-control", placeholder: "Gist description…" %>
      </div>

      <div id="files">
        <%= form.fields_for :files do |file_form| %>
          <%= render "file_fields", f: file_form %>
        <% end %>
      </div>

      <div class="form-check">
        <%= form.check_box :public, class: "form-check-input" %>
        <%= form.label :public, "Create public gist", class: "form-check-label" %>
      </div>

      <div class="row mt-3">
        <div class="col-auto mr-auto">
          <%= link_to_add_association "Add File", form, :files,
            class: "btn btn-outline-secondary",
            "data-association-insertion-node" => "#files",
            "data-association-insertion-method" => "append"
          %>
        </div>
        <div class="col-auto right-gap">
          <%= form.submit "Create", class: "btn btn-outline-primary" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/dashboard/star_gist.js.erb
$('<%= "#icon-#{params[:id]}"%>').toggleClass('far fas');
$('<%= "#link-#{params[:id]}"%>').attr("href", "<%= unstar_gist_path(id: params[:id]) %>");

app/views/dashboard/unstar_gist.js.erb
$('<%= "#icon-#{params[:id]}"%>').toggleClass('fas far');
$('<%= "#link-#{params[:id]}"%>').attr("href", "<%= star_gist_path(id: params[:id]) %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GistCatch</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
  </head>
  <body>
    <div class="container">
      <header>
        <% if user_signed_in? %>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <%= image_tag "logo_transparent_new.png", width: 50, style: "margin-right: 10px;" %>
          <%= link_to "Gist Catch", root_path, {class: "navbar-brand nav-header"}%>
          <div class="align-right">
            <%= link_to 'My Gists', gists_path(current_client.login), {class: 'btn btn-outline-secondary btn-sm'}%>
            <%= link_to 'New Gist', new_gist_path, class: 'btn btn-outline-secondary btn-sm' %>
            <%= link_to 'Sign out', destroy_user_session_path, {method: 'delete', class: 'btn btn-outline-secondary btn-sm'}%>
          </div>
        </nav>
        <% end %>
      </header>
      <main role="main" class="top-gap">
        <%= render "alert" %>
        <%= yield %>
      </main>
    </div>
  </body>
</html>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <%= image_tag "logo_transparent_new.png", width: 400, style: "margin-right: 10px;" %>
  <h1 class="display-3">Your Gist Friend</h1>
  <p class="lead">Can help you to manage your Gists out of Gist</p>
  <p><%= link_to omniauth_authorize_path(:user, "github"), {class: "btn btn-success", role: "button"} do%>
      <i class="fab fa-github"></i> Sign in with Github
    <% end %>
  </p>
</div>